version: latest

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "python manage.py migrate &&
             gunicorn publication.wsgi:application --bind 0.0.0.0:$PORT"
    ports:
      - 8000:8000
    

  

volumes:
  static: