version: latest

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "python manage.py migrate &&
             daphne -b 0.0.0.0 -p 8000 card_backend.asgi:application"
    ports:
      - 8000:8000
    environment:
      - REDIS_NETWORK=redis
    depends_on:
      - redis
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    

  

volumes:
  static: