version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - HOST=publications.cj2olckjerwl.eu-north-1.rds.amazonaws.com
      - USER=${USER}
      - PASSWORD=fierylion
    command: >
      sh -c "python manage.py migrate &&
             daphne -b 0.0.0.0 -p 8000 card_backend.asgi:application"
    ports:
      - 8000:8000

    depends_on:
      - redis
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    

  

volumes:
  static: