version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - HOST=${HOST}
      - USER=${USER_NAME}
      - PASSWORD=${PASSWORD}
      - DB_PORT=${DB_PORT}
      - SECRET_KEY=${SECRET_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - NAME=${NAME}
    command: >
      sh -c "python manage.py migrate &&
             daphne -b 0.0.0.0 -p 8000 card_backend.asgi:application"
    ports:
      - 80:8000

    depends_on:
      - redis
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    

  

volumes:
  static: