name: Deploy to Digital Ocean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass && sudo apt-get install -y lftp

      - name: Run commands on the Droplet
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
          SSH_IP: ${{ secrets.SSH_IP }}

      - name: SSH into the Droplet
        env:
          SSH_HOST: ${{secrets.SSH_USER}}
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
          SSH_IP: ${{ secrets.SSH_IP }}

        run: |
          sshpass -p $SSH_PASSWORD ssh $SSH_USER@$SSH_IP 

