name: Deploy to Digital Ocean



on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH into the Droplet
        env:
          SSH_HOST: ${{secrets.SSH_USER}}
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
          SSH_IP: ${{ secrets.SSH_IP }}

        run: |
           ssh root@$159.223.10.77 "echo 'Logged in to the droplet'"
